version: '3.7'
services:
  application:
    build: ./
    volumes:
      - './:/var/www'
    ports:
      - '80:80'
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'foraging'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
volumes:
  database: